### ISSUE TITLE
Re-center camera not working

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/Evident-initial-demo#12]
When rotating a PCoA plot and trying to use the Recenter Camera button in the Options tab, the camera is not completely re-centered.

It was mentioned that this issue could be caused given a bug in [Three](https://github.com/mrdoob/three.js/).

**Comment by megalodonatron** [comment]
Can you link to something describing the bug?

**Comment by ElDeveloper** [comment]
Using the Fierer et. al. Keyboard demo visualization:

With the dataset as it comes from the demo visualization:
![first](http://i.imgur.com/rcypJ.png)

If you rotate the plot in a random way:
![second](http://i.imgur.com/fGLFq.png)

After using the re-center camera button:
![third](http://i.imgur.com/3sDow.png)

I would have expected the third picture to look like the first one.

**Comment by megalodonatron** [comment]
I meant an example of the three.js bug. The way I have to code in evident is that it uses the same line of code it does to set up the camera in the first place, so I don't know what else to change to make it look like the first one.

**Comment by ElDeveloper** [comment]
Oh I wouldn't know the specifics from three.js, though I recall that @antgonza mentioned this could be because of an outdated version of three.js though I might be wrong. 

Probably mentioning the issue on the tree.js github site, opening an issue maybe?

**Comment by megalodonatron** [comment]
This is a known bug in three.js https://github.com/mrdoob/three.js/issues/821

**Comment by ElDeveloper** [comment]
Bump, https://github.com/mrdoob/three.js/issues/821 seems to have been fixed in the master repo in https://github.com/mrdoob/three.js/pull/3073 Perhaps worth updating the version of the files within E-vident.

**Comment by antgonza** [comment]
+1

**Comment by ElDeveloper** [comment]
Fixed in #40.
