### ISSUE TITLE
Error in coloring due to non alphanumeric characters

### ISSUE THREAD

**Issue by antgonza** [biocore/Evident-initial-demo#35]
When the categories of a column in the mapping file has no alphanumeric characters (for example '), the coloring by metadata doesn't work.

**Comment by ElDeveloper** [comment]
I have noticed this problem as well in [emperor](github.com/qiime/emperor) should this issue be moved there or duplicated?

**Comment by antgonza** [comment]
Suggest adding in emperor and fix in either place; then copy the solution
to the other software.
