### ISSUE TITLE
Add test code

### ISSUE THREAD

**Issue by megalodonatron** [biocore/Evident-initial-demo#7]
Add test code

**Comment by ElDeveloper** [comment]
Which specific part of the software needs testing?

**Comment by megalodonatron** [comment]
Just the scripts in evident, which you did already. You can close this issue.

**Comment by ElDeveloper** [comment]
It's fine `evident/rarefaction.py` is not tested yet. I'm working on this tests and re-working this module, will hopefully issue a pull request regarding this later today or tomorrow.

**Comment by ElDeveloper** [comment]
At this point all the code seems to have the proper testing scripts, I will close this issue.
